import React from 'react';
import {
  FaFilePdf,
  FaHandsHelping,
  FaRupeeSign,
  FaSignal,
  FaUser,
  FaLinkedinIn,
  FaRegHandshake,
  FaRegHeart,
  FaStar,
  FaFacebookMessenger,
  FaSms,
  FaArrowLeft,
  FaRegPlusSquare,
} from 'react-icons/fa';
import { IoLogoWhatsapp, IoMdHome } from 'react-icons/io';
import { FaRegSquareMinus } from 'react-icons/fa6';
import { FiCheckCircle, FiMapPin, FiUsers } from 'react-icons/fi';
import { TbCalendarStats, TbCameraPlus } from 'react-icons/tb';
import { TfiViewList } from 'react-icons/tfi';
import { LuCopyCheck } from 'react-icons/lu';
import {
  BsCalendarPlus,
  BsCheckLg,
  BsChevronDown,
  BsChevronLeft,
  BsChevronRight,
  BsDownload,
  BsEmojiSmile,
  BsFillCheckCircleFill,
  BsTag,
  BsThreeDotsVertical,
  BsArrowLeft,
  BsArrowRight,
  BsThreeDots,
  BsGenderMale,
  BsPerson,
  BsGraphUpArrow,
  BsCalendarX,
  BsApple,
  BsDiscord,
  BsQrCode,
  BsPeople,
  BsShareFill,
  BsRobot,
} from 'react-icons/bs';
import {
  BiLogOutCircle,
  BiDollarCircle,
  BiInfoCircle,
  BiPlus,
  BiMinus,
  BiSearch,
  BiHomeAlt2,
  BiCalendarAlt,
  BiWallet,
  BiLogoPlayStore,
  BiLogoTelegram,
  BiLogoLinkedin,
  BiLogoYoutube,
  BiPowerOff,
  BiLogoFacebook,
  BiSolidDownArrow,
  BiChevronDown,
} from 'react-icons/bi';
import {
  AiFillCustomerService,
  AiOutlineTwitter,
  AiFillEye,
  AiFillEyeInvisible,
  AiFillLayout,
  AiFillStar,
  AiOutlineSetting,
  AiOutlineStar,
  AiOutlineUnorderedList,
  AiOutlineUsergroupAdd,
  AiOutlineCloseCircle,
  AiFillInstagram,
  AiOutlineClockCircle,
} from 'react-icons/ai';
import {
  MdClose,
  MdDashboard,
  MdDelete,
  MdEdit,
  MdOutlineAnalytics,
  MdOutlineContentCopy,
  MdPublishedWithChanges,
  MdRocketLaunch,
  MdOutlineWorkOutline,
  MdOutlineOtherHouses,
  MdDateRange,
  MdAttachMoney,
  MdFavoriteBorder,
  MdLockOutline,
  MdOutlineSportsCricket,
  MdOutlineCasino,
  MdCalendarMonth,
  MdCalendarToday,
  MdOutlineRealEstateAgent,
} from 'react-icons/md';

import { ImQuotesLeft } from 'react-icons/im';
import {
  HiDocumentReport,
  HiMenu,
  HiOutlineDocumentReport,
} from 'react-icons/hi';
import { GoVerified } from 'react-icons/go';
import {
  RiSecurePaymentLine,
  RiFlashlightLine,
  RiFootballLine,
} from 'react-icons/ri';
import { PiSquaresFour } from 'react-icons/pi';
import { IoFootball, IoReceiptOutline } from 'react-icons/io5';
import { SlPlane } from 'react-icons/sl';
import { VscTriangleDown } from 'react-icons/vsc';

export const reactIcons = {
  arrowleft1: <FaArrowLeft />,
  bot: <BsRobot />,
  share: <BsShareFill />,
  money: <MdAttachMoney />,
  people: <BsPeople />,
  trading: <BsGraphUpArrow />,
  power: <BiPowerOff />,
  apple: <BsApple />,
  star2: <FaStar />,
  playstore: <BiLogoPlayStore />,
  offline: <BsCalendarX />,
  close1: <AiOutlineCloseCircle />,
  user: <FaUser />,
  logout: <BiLogOutCircle />,
  dollar: <BiDollarCircle />,
  list: <AiOutlineUnorderedList />,
  arrowleft: <BsChevronLeft />,
  arrowright: <BsChevronRight />,
  arrowdown: <BsChevronDown />,
  success: <BsFillCheckCircleFill />,
  pdf: <FaFilePdf />,
  info: <BiInfoCircle />,
  dashboard: <MdDashboard />,
  layouts: <AiFillLayout />,
  reports: <HiDocumentReport />,
  verify: <GoVerified />,
  publish: <MdPublishedWithChanges />,
  plus: <BiPlus />,
  minus: <BiMinus />,
  rupee: <FaRupeeSign />,
  copy: <MdOutlineContentCopy />,
  copied: <LuCopyCheck />,
  edit: <MdEdit />,
  delete: <MdDelete />,
  search: <BiSearch />,
  news: <MdRocketLaunch />,
  home: <BiHomeAlt2 />,
  homeFill: <IoMdHome />,
  calendar: <BiCalendarAlt />,
  sales: <BsTag />,
  customer: <BsEmojiSmile />,
  analytics: <MdOutlineAnalytics />,
  staff: <FiUsers />,
  setup: <AiOutlineSetting />,
  services: <AiFillCustomerService />,
  empty: <FaSignal />,
  timeCalendar: <TbCalendarStats />,
  download: <BsDownload />,
  close: <MdClose />,
  camera: <TbCameraPlus />,
  listNestedBox: <AiOutlineUnorderedList />,
  listBox: <TfiViewList />,
  menu: <HiMenu />,
  threeDots: <BsThreeDotsVertical />,
  eyeslash: <AiFillEyeInvisible />,
  eyes: <AiFillEye />,
  location: <FiMapPin />,
  successCheck: <FiCheckCircle />,
  check: <BsCheckLg />,
  importUser: <AiOutlineUsergroupAdd />,
  addCalendar: <BsCalendarPlus />,
  helpCenter: <FaHandsHelping />,
  star: <AiOutlineStar />,
  fillstar: <AiFillStar />,
  work: <MdOutlineWorkOutline />,
  other: <MdOutlineOtherHouses />,
  left: <BsArrowLeft />,
  right: <BsArrowRight />,
  dot3: <BsThreeDots />,
  wallet: <BiWallet />,
  date: <MdDateRange />,
  insta: <AiFillInstagram />,
  facebook: <BiLogoFacebook />,
  linkdin: <FaLinkedinIn />,
  twitter: <AiOutlineTwitter />,
  queto: <ImQuotesLeft />,
  clock: <AiOutlineClockCircle />,
  paybyapp: <RiSecurePaymentLine />,
  male: <BsGenderMale />,
  flash: <RiFlashlightLine />,
  hands: <FaRegHandshake />,
  person: <BsPerson />,
  fav: <MdFavoriteBorder />,
  heart: <FaRegHeart />,
  telegram: <BiLogoTelegram />,
  discord: <BsDiscord />,
  linkedin: <BiLogoLinkedin />,
  youtube: <BiLogoYoutube />,
  qrcode: <BsQrCode />,
  arrowdownFill: <BiSolidDownArrow />,
  portfolio: <HiOutlineDocumentReport />,
  whatsapp: <IoLogoWhatsapp />,
  messenger: <FaFacebookMessenger />,
  sms: <FaSms />,
  lock: <MdLockOutline />,
  fourSquare: <PiSquaresFour />,
  calender2: <MdCalendarMonth />,
  football: <IoFootball />,
  cricket: <MdOutlineSportsCricket />,
  casino: <MdOutlineCasino />,
  receipt: <IoReceiptOutline />,
  aviator: <SlPlane />,
  triangleDown: <VscTriangleDown />,
  arrowDown: <BiChevronDown />,
  square: <FaRegPlusSquare />,
  minusBtn: <FaRegSquareMinus />,
  navToday: <MdCalendarToday />,
  navFootaball: <RiFootballLine />,
  navCricket: <MdOutlineSportsCricket />,
  navCasino: <MdOutlineCasino />,
  navAgent: <MdOutlineRealEstateAgent />,
};
